require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
  - rubocop-thread_safety

AllCops:
  NewCops: enable

Metrics/MethodLength:
  Enabled: true
  CountComments: false
  Max: 10
  CountAsOne:
    - array
    - hash
    - heredoc
